#! /bin/bash

PATH_CREATE_FILE="${BASE_DIR}/scripts/tcl/create.tcl"

EXEC_CREATE="${PATH_HDB_TCLSH} ${PATH_CREATE_FILE} ${HOST} ${PORT} ${SUPER_USER_NAME} ${SUPER_USER_PASS} ${ADMIN_DB_NAME} ${WAREHOUSES} ${USERS} ${DB_NAME} ${DB_USER} ${DB_USER_PASS}"

time eval "${EXEC_CREATE}"